services:
  api:
    environment:
      - BD=${NAME_CONTAINER_DB}

    container_name: ${NAME_CONTAINER_API}
    
    build:
      context: .
      dockerfile: api.dockerfile
    
    ports:
      - "${PORT_API}:${PORT_API}"
    
    networks:
      - base_network

    volumes:
      - .:/api
      - .:/api/node_modules

    depends_on: 
      - mysql

    command: sh - c "npx prisma migrate deploy && npm start"
    
  mysql:
    container_name: ${NAME_CONTAINER_DB}
    
    image: ${IMAGE_BD}

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    ports:
      - "${PORT_DB}:${PORT_DB}"

    expose:
      - ${PORT_DB}

    networks:
      - base_network

    volumes:
      - my_db:/var/lib/mysql

networks:
  base_network:
    driver: bridge


volumes:
  my_db: 